# Example pod definition using secrets, for an app that needs to connect to a DB
apiVersion: v1
kind: Pod
metadata:
  name: my-app
  labels:
    type: application
spec:
  containers:
    - name: my-app
      image: my-app:v1.2

# Note on the differences between 'env:' and 'envFrom:'
# 'env:' is used when we want to specify keys from specific files.
# 'envFrom:' is used when we want to pass an entire ConfigMap/Secret file(s) to the pod
# See the example comparing the two formats at the bottom of the page
      env:
        - name: DB_USER               # This is the name of the env variable in the pod, not the key in the secret file
          valueFrom:
            secretKeyRef:
              name: my-db-secrets     # This is the name specified in the metadata of the secret file
              key: user               # Like ConfigMaps, we can specify a specific k-v
        - name: DB_PASSWD
          valueFrom:
            secretKeyRef:
              name: my-db-secrets
              key: pw

# Example using 'env':
# ...
# spec:
#   containers:
#     ...
#     ...
#     env:
#       - name: DB_USER
#         valueFrom:
#           secretKeyRef:
#             name: my-db-secrets
#             key: user
#       - name: DB_PORT       # We can mix different types. Here we specify a ConfigMap var.
#         valueFrom:
#           configMapKeyRef:
#             name: my-db-configmap
#             key: port
#       - name: DB_NAME       # We can also specify env vars directly, although this is not best practice in my opinion
#         value: my-app
#
#
# In comparison, 'envFrom:' just passes the name of the secret/configmap and injects everything.
# ...
# spec:
#   containers:
#     ...
#     ...
#     envFrom:
#       - secretRef:                  # or configMapRef
#           name: my-db-secrets
#       - secretRef:
#           name: my-other-db-secrets
#       - configMapRef:
#           name: my-db-configmap
