# Another example of secrets in Kubernetes
apiVersion: v1
kind: Secret
metadata:
  name: my-db-secrets       # We will reference this in our pod definition

# You can create these base64 encoded 'secrets' with: echo -n '<your-secret>' | base64 >> secret-file.yml
# You can also decode with the base64 --decode option, which is why they are not truly secure
data:
  user: ZGF0YWJhc2UtdXNlcg==
  pw: ZGF0YWJhc2UtcHc=
