# Example of secrets in k8s. This method is weaker than external kms, and probably is only good for dev environments
apiVersion: v1
kind: Secret
metadata:
  name: my-secret
data:
  User: c2VjcmV0LXVzZXI=      # base64 encoded 'secret-user'
  Pw: c2VjcmV0LXBhc3N3b3Jk    # base64 encoded 'secret-password'

# To use this in a pod, the pod spec looks like:
# ...
# spec:
#   containers:
#     - name: my-app
#       image: my-app-image
#       ports:
#         - containerPort: 8080
#       envFrom:
#         - secretRef:
#             name: my-secret       # This passes the secret above based on the name we gave it 
