# Example ServiceAccount definition file
# Note that this is a very basic example, and service account management on its own is a much broader and complex topic.
apiVersion: v1
kind: ServiceAccount
metadata:
  name: service-account-01

# By default, the kubelet will automount the service account's API credentials at /var/run/secrets/kubernetes.io/serviceaccount/token
# To change this behavior, include the field below and set the value to false.
automountServiceAccountToken: false

---

# To use a service account in a pod spec, see the example below.
# Note that if both the ServiceAccount and the Pod's .spec specify a value for automountServiceAccountToken, the Pod spec takes precedence.
# ...
# spec:
#   serviceAccountName: service-account-01
#   automountServiceAccountToken: false       # Optional
#   ...

---

# Launching a pod with service account token projection - Example from the k8s documentation
# For more info, see https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/
# apiVersion: v1
# kind: Pod
# metadata:
#   name: nginx
# spec:
#   containers:
#   - image: nginx
#     name: nginx
#     volumeMounts:
#     - mountPath: /var/run/secrets/tokens
#       name: vault-token
#   serviceAccountName: build-robot
#   volumes:
#   - name: vault-token
#     projected:
#       sources:
#       - serviceAccountToken:
#           path: vault-token
#           expirationSeconds: 7200
#           audience: vault

