# This is an example of a kubeconfig file, which is stored in $HOME/.kube/config
# It is used to specify various parameters for a user when they invoke the kubectl command
# It has 3 key fields - cluster, context, and users
apiVersion: v1
kind: Config
currentContext: admin@production    # This optional field specifies the default context for kubectl. Useful if you have several clusters. 
clusters:
  - name: production
    cluster:
      certificate-authority: /etc/kubernetes/pki/ca.crt   # You can provide the cert directly using certificate-authority-data: <Base-64 Encoded Value>
      server: https://prod-k8s.internal:6443              # You can also use IP address here

context:
  - name: admin@production
    context:
      cluster: production
      user: admin
      namespace: ns-01        # Optional field, which defines the default namespace

users:
  - name: admin
    user:
      client-certificate: /etc/kubernetes/pki/users/admin.crt
      client-key: /etc/kubernetes/pki/users/admin.key

# You can update the context with `kubectl config use-context user@other-cluster`. This will update the currentContext field in the file
# You can view the kubeconfig with `kubectl config view`
